### ISSUE TITLE
Cannot read properties of undefined (reading 'ENABLE')

### ISSUE THREAD

**Issue by acodreanu** [wojtekmaj/react-pdf#1194]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Hi!

I am getting this:
```
PageCanvas.js:64 Uncaught TypeError: Cannot read properties of undefined (reading 'ENABLE')
    at PageCanvasInternal.drawPageOnCanvas (PageCanvas.js:64:1)
    at PageCanvasInternal.componentDidMount (PageCanvas.js:85:1)
    at commitLifeCycles (react-dom.development.js:20663:1)
    at commitLayoutEffects (react-dom.development.js:23426:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at commitRootImpl (react-dom.development.js:23151:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at commitRoot (react-dom.development.js:22990:1)
    at performSyncWorkOnRoot (react-dom.development.js:22329:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at scheduleUpdateOnFiber (react-dom.development.js:21893:1)
    at Object.enqueueSetState (react-dom.development.js:12467:1)
    at push../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:365:1)
    at Page.js:78:1
```
    
Note: If I revert to 5.x, everything works fine. Any ideas?

### Steps to reproduce

This happens once react-pdf loads in my app. I've noticed this happens only from version 6.x. I am using react-scripts@4.0.0, I am importing the worker from an external CDN, installed `file-loader` manually and I am importing from `react-pdf/dist/esm/entry.webpack`. I'm also doing a very basic scenario with one Document and a single page with navigation buttons.
    

### Expected behavior

To work.

### Actual behavior

Throws at first load:
```
PageCanvas.js:64 Uncaught TypeError: Cannot read properties of undefined (reading 'ENABLE')
    at PageCanvasInternal.drawPageOnCanvas (PageCanvas.js:64:1)
    at PageCanvasInternal.componentDidMount (PageCanvas.js:85:1)
    at commitLifeCycles (react-dom.development.js:20663:1)
    at commitLayoutEffects (react-dom.development.js:23426:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at commitRootImpl (react-dom.development.js:23151:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at commitRoot (react-dom.development.js:22990:1)
    at performSyncWorkOnRoot (react-dom.development.js:22329:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at scheduleUpdateOnFiber (react-dom.development.js:21893:1)
    at Object.enqueueSetState (react-dom.development.js:12467:1)
    at push../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:365:1)
    at Page.js:78:1
    ```

### Environment

- **Browser (if applicable)**: Latest Chrome
- **React-PDF version**:
- **React version**: 17.0.2
- **Webpack version (if applicable)**: Webpack 4

**Comment by acodreanu** [comment]
You are right. I had a duplicate. Thank you so much!
