### ISSUE TITLE
Got error on server-side rendering

### ISSUE THREAD

**Issue by againksy** [wojtekmaj/react-pdf#153]
ReferenceError: window is not defined
    at /srv/dreamstudy_frontend/node_modules/react-pdf/node_modules/pdfjs-dist/lib/web/ui_utils.js:391:3
    at new WrappedPromise (/usr/lib/node_modules/pm2/node_modules/async-listener/es6-wrapped-promise.js:13:18)
    at Object.<anonymous> (/srv/dreamstudy_frontend/node_modules/react-pdf/node_modules/pdfjs-dist/lib/web/ui_utils.js:390:24)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/srv/dreamstudy_frontend/src/_server/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module_load (/usr/lib/node_modules/pm2/node_modules/vxx/src/trace-plugin-loader.js:177:33)

**Comment by wojtekmaj** [comment]
Hey there,
SSR is supported in 3.x, which is close to being released. Check it out, and leave some feedback at #143! :)

**Comment by vladgolubev** [comment]
@wojtekmaj did you test SSR before releasing 3.x? If so, do you have any example code by chance?

**Comment by wojtekmaj** [comment]
@vladgolubev, it's generally hard to do anything with React-PDF on SSR. There's no way to send a proper, filled in canvas from the server. You just gotta render that browser side. You can experiment with rendering pages as SVG though - this could work.

**Comment by vladgolubev** [comment]
@wojtekmaj thanks for the response!

Just did a quick search - and looks like a show stopper indeed - https://github.com/mozilla/pdf.js/issues/565

![image](https://user-images.githubusercontent.com/3817380/38642435-bf327b24-3de2-11e8-96b7-7903f27276f9.png)
