### ISSUE TITLE
Error: Cannot find module 'core-js/fn/object/values'

### ISSUE THREAD

**Issue by againksy** [wojtekmaj/react-pdf#154]
Stack Trace:
Error: Cannot find module 'core-js/fn/object/values'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module_load (/usr/lib/node_modules/pm2/node_modules/vxx/src/trace-plugin-loader.js:172:33)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:94:21)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at checkObjectValues (/srv/dreamstudy_frontend/node_modules/react-pdf/node_modules/pdfjs-dist/lib/shared/compatibility.js:709:21)
    at Object.<anonymous> (/srv/dreamstudy_frontend/node_modules/react-pdf/node_modules/pdfjs-dist/lib/shared/compatibility.js:710:5)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/srv/dreamstudy_frontend/src/_server/node_modules/babel-register/lib/node.js:152:7)

**Comment by wojtekmaj** [comment]
Hey there,
that sounds like a bad npm install. Have you tried completely removing your node_modules and reinstalling?

**Comment by wojtekmaj** [comment]
Hey @againksy,
I'm closing this issue to give active issues more visibility. If you still have this issue and want to talk, I'll be happy to reopen.
Cheers!
