### ISSUE TITLE
Module not found: 'worker-loader' when using create-react-app

### ISSUE THREAD

**Issue by SrikanthChebrolu** [wojtekmaj/react-pdf#155]
Error in ./~/pdfjs-dist/webpack.js
Module not found: 'worker-loader' in /Users/srikanthchebrolu/Developer/Project/srikanthchebrolu/node_modules/pdfjs-dist

 @ ./~/pdfjs-dist/webpack.js 18:18-64

I used create-react-app to generate the project where webpack is not available directly. Can someone help me with this problem?

**Comment by wojtekmaj** [comment]
Hmmm. I don't have much experience with create-react-app, but maybe try installing worker-loader as a separate package?

**Comment by wojtekmaj** [comment]
Hey @SrikanthChebrolu,
did my suggestion work?
I'm closing this issue to give active issues more visibility. If you still have this issue and want to talk, I'll be happy to reopen.
Cheers!

**Comment by liviuignat** [comment]
@wojtekmaj  Actually not working. Using `webpack@3.8.1`, tried with version `3.x` and `4.x` and I get the same issue. Would be great if you have any tips.

```
Cannot find module 'worker-loader!./pdf.worker.entry.js'
[0]     at Function.Module._resolveFilename (module.js:547:15)
[0]     at Function._module2.default._resolveFilename ({projectPath}/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:442:34)
[0]     at Function.Module._load (module.js:474:25)
[0]     at Module.require (module.js:596:17)
[0]     at require (internal/module.js:11:18)
[0]     at Object.<anonymous> ({projectPath}/node_modules/react-pdf/dist/entry.webpack.js:24:23)
[0]     at Module._compile (module.js:652:30)
[0]     at Module._extensions..js (module.js:663:10)
[0]     at Object.require.extensions.(anonymous function) [as .js] ({projectPath}/node_modules/babel-register/lib/node.js:152:7)
[0]     at Module.load (module.js:565:32)
```

**Comment by liviuignat** [comment]
Update, if anyone else needs it, in webpack use
```
resolve: {
    alias: { 'react-pdf': 'react-pdf/dist/entry.webpack' },
   ....
  },
```

then just import `import { Document, Page } from 'react-pdf';`

**Comment by wojtekmaj** [comment]
Hello,
Create React App 1.x will never support worker-loader, so you need to use generic instructions.

Create React App 2 will support worker-loader once facebook/create-react-app#3934 gets merged.
