### ISSUE TITLE
Unable to resolve module `url` from `.../node_modules/pdfjs-dist/build/pdf.js

### ISSUE THREAD

**Issue by oukano** [wojtekmaj/react-pdf#318]
**Before you start - checklist**

 - [ ] I have read documentation in README
 - [ ] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [ ] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

and then i tried . to start the application on a virtuel device, and BOOM 

```
The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
{"originModulePath":"/Users/imac1/Desktop/PDF2/node_modules/pdfjs-dist/build/pdf.js","targetModuleName":"url","message":"Unable to resolve module `url` from `/Users/imac1/Desktop/PDF2/node_modules/pdfjs-dist/build/pdf.js`: Module `url` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.\n  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.","errors":[{"description":"Unable to resolve module `url` from `/Users/imac1/Desktop/PDF2/node_modules/pdfjs-dist/build/pdf.js`: Module `url` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.\n  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`."}],"name":"Error","stack":"Error: Unable to resolve module `url` from `/Users/imac1/Desktop/PDF2/node_modules/pdfjs-dist/build/pdf.js`: Module `url` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.\n  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.\n    at ModuleResolver.resolveDependency (/Users/imac1/Desktop/PDF2/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:139:15)\n    at ResolutionRequest.resolveDependency (/Users/imac1/Desktop/PDF2/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:49:18)\n    at DependencyGraph.resolveDependency (/Users/imac1/Desktop/PDF2/node_modules/metro/src/node-haste/DependencyGraph.js:219:16)\n    at Object.resolve (/Users/imac1/Desktop/PDF2/node_modules/metro/src/lib/transformHelpers.js:141:30)\n    at dependencies.map.result (/Users/imac1/Desktop/PDF2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:373:31)\n    at Array.map (<anonymous>)\n    at resolveDependencies (/Users/imac1/Desktop/PDF2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:369:18)\n    at /Users/imac1/Desktop/PDF2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:188:33\n    at Generator.next (<anonymous>)\n    at step (/Users/imac1/Desktop/PDF2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:30)"}
processBundleResult
    BundleDownloader.java:296
access$200
    BundleDownloader.java:37
onResponse
    BundleDownloader.java:174
execute
    RealCall.java:153
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1162
run
    ThreadPoolExecutor.java:636
run
    Thread.java:764
```

**Describe solutions you've tried**

i've tried to delete npm and reinstall again and  clear the cache but still the same

**Additional information**

![capture d ecran 2018-12-07 a 09 58 26](https://user-images.githubusercontent.com/13186110/49637864-dbd95000-fa06-11e8-9612-6513e186bb67.png)

**Environment**

 
 - React-PDF version [e.g. 3.0.4]: latest
 - React version [e.g. 16.3.0]: latest
 - Webpack version (if applicable) [e.g. 4.16.2]: no webpack

**Comment by wojtekmaj** [comment]
Looks like you're using React Native. I don't think React-PDF would work on React Native.

**Comment by oukano** [comment]
sorry man
