### ISSUE TITLE
SSR error

### ISSUE THREAD

**Issue by EnrikoLabriko** [wojtekmaj/react-pdf#76]
Hello, it seems I need your help

I have two projects: isomorphic React SPA and stateless UI components library. When I use `react-pdf` in the library, it's ok, but when I try to use my wrapper component which depends on `react-pdf` in the SPA, it fails.

This is the full trace:
```
.../tb-react-front/node_modules/teachbase-ui/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { module.exports=function(modules){function __webpack_require__(moduleId){if(installedModules[moduleId])return installedModules[moduleId].exports;var module=installedModules[moduleId]={i:moduleId,l:!1,exports:{}};return modules[moduleId].call(module.exports,module,module.exports,__webpack_require__),module.l=!0,module.exports}var parentJsonpFunction=window.webpackJsonpteachbase_ui;window.webpackJsonpteachbase_ui=function(chunkIds,moreModules,executeModules){for(var moduleId,chunkId,i=0,resolves=[];i<chunkIds.length;i++)chunkId=chunkIds[i],installedChunks[chunkId]&&resolves.push(installedChunks[chunkId][0]),installedChunks[chunkId]=0;for(moduleId in moreModules)Object.prototype.hasOwnProperty.call(moreModules,moduleId)&&(modules[moduleId]=moreModules[moduleId]);for(parentJsonpFunction&&parentJsonpFunction(chunkIds,moreModules,executeModules);resolves.len

ReferenceError: window is not defined
    at /Users/labriko/Work/Teachbase/Teachbase3/tb-react-front/node_modules/teachbase-ui/lib/index.js:1:357
    at Object.<anonymous> (/Users/labriko/Work/Teachbase/Teachbase3/tb-react-front/node_modules/teachbase-ui/lib/index.js:1:2648)
    at Module._compile (module.js:624:30)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/labriko/Work/Teachbase/Teachbase3/tb-react-front/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Module._load (module.js:500:3)
    at Function.module._load (/Users/labriko/Work/Teachbase/Teachbase3/tb-react-front/node_modules/piping/lib/piping.js:218:16)
    at Module.require (module.js:568:17)
```

The problem is here (window is undefined in Node):
```
var parentJsonpFunction=window.webpackJsonpteachbase_ui;
```

Does react-pdf cause this error? When I remove `react-pdf` everything gets well
Thank you

**Comment by wojtekmaj** [comment]
Hey,
it doesn't seem to be related directly to react-pdf. In fact, it does not use webpack directly at all. I'd suggest seeking help with teachbase-ui developers instead.

**Comment by EnrikoLabriko** [comment]
Thanks for your answer

`teachbase-ui` is the UI lib I meant and I'm a maintainer of it and SPA as well. So, `react-pdf` works fine with `teachbase-ui` as dependency, but crashes SPA as second level dependency:
![image](https://user-images.githubusercontent.com/6498649/31090392-2c78bc8a-a7b0-11e7-8971-713459436d80.png)
