### ISSUE TITLE
 WebpackError: Call retries were exceeded & Window is not defined

### ISSUE THREAD

**Issue by abhaybriskteq** [wojtekmaj/react-pdf#765]
My project is based on gatsby-website. When I run gatsby build command it will gives following error.

ReferenceError: window is not defined
    at D:\Project\public\render-page.js:40343:3
    at new Promise (<anonymous>)
    at Object../node_modules/pdfjs-dist/lib/web/ui_utils.js (D:\Project\public\render-page.js:40342:26)
    at __webpack_require__ (D:\Project\public\render-page.js:48610:42)
    at Object../node_modules/pdfjs-dist/lib/web/pdf_link_service.js (D:\Project\public\render-page.js:39345:17)
    at __webpack_require__ (D:\Project\public\render-page.js:48610:42)
    at Module../node_modules/react-pdf/dist/esm/LinkService.js (D:\Project\public\render-page.js:44030:93)
    at __webpack_require__ (D:\Project\public\render-page.js:48610:42)
    at Module../node_modules/react-pdf/dist/esm/Document.js (D:\Project\public\render-page.js:43465:71)
    at __webpack_require__ (D:\Project\public\render-page.js:48610:42)
    at Module../node_modules/react-pdf/dist/esm/entry.webpack.js (D:\Project\public\render-page.js:46496:67)
    at __webpack_require__ (D:\Project\public\render-page.js:48610:42)
    at Module../src/routes/default/index.js (D:\Project\public\render-page.js:7404:90)
    at __webpack_require__ (D:\Project\public\render-page.js:48610:42)
    at Object../.cache/_this_is_virtual_fs_path_/$virtual/sync-requires.js (D:\Project\public\render-page.js:6740:
116)
failed Building static HTML for pages - 1.672s

 ERROR #95313

Building static HTML failed

See our docs page for more info on this error: https://gatsby.dev/debug-html

  10 |
  11 | export default function _createClass(Constructor, protoProps, staticProps) {
> 12 |   if (protoProps) _defineProperties(Constructor.prototype, protoProps);
     | ^
  13 |   if (staticProps) _defineProperties(Constructor, staticProps);
  14 |   return Constructor;
  15 | }

  WebpackError: Call retries were exceeded

  - createClass.js:12
    [myapp]/[@babel]/runtime/helpers/esm/createClass.js:12:1

I used react-pdf version react-pdf 5.2.0.

and  import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';

I cannot get the issue.  I checked everywhere, I used window !== 'undefined' && window.xyz condition. 
Before 10 days it is working perfectly and Now it is not working.

**Comment by from74** [comment]
Same issue without '... dist/esm/entry.webpack' :(

**Comment by hornetDC** [comment]
I was getting this error, updated from 5.2 to 5.3. Now I am getting this error instead:

```
Can't resolve 'canvas' in 'C:\Users\xandg\Projects\xp-monorepo\packages\broker-site-admin\node_modules\pdfjs-dist\build'

If you're trying to use a package make sure that 'canvas' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules\pdfjs-dist\build\pdf.js
```

**Comment by pachkovska** [comment]
I am getting same error as @hornetDC  and did not find a solution yet.

**Comment by Fouppy** [comment]
Same here, I tried `renderMode="svg"` to no avail

**Comment by wojtekmaj** [comment]
Duplicate of #113
