### ISSUE TITLE
Error: write EPIPE at afterWriteDispatched (internal/stream_base_commons.js:156:25)

### ISSUE THREAD

**Issue by tiennguyen1293** [wojtekmaj/react-pdf#802]
it's seems related to node-html-pdf issue [35](https://github.com/marcbachmann/node-html-pdf/issues/35)

**Before you start - checklist**
```
yarn run v1.22.5
$ node scripts/build.js
Creating an optimized production build...
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at PoolWorker.writeJson (/home/botci/project/node_modules/thread-loader/dist/WorkerPool.js:89:22)
    at PoolWorker.run (/home/botci/project/node_modules/thread-loader/dist/WorkerPool.js:69:12)
    at WorkerPool.distributeJob (/home/botci/project/node_modules/thread-loader/dist/WorkerPool.js:326:20)
    at /home/botci/project/node_modules/async/queue.js:10:5
    at Object.process (/home/botci/project/node_modules/async/internal/queue.js:175:17)
    at /home/botci/project/node_modules/async/internal/queue.js:115:15
    at /home/botci/project/node_modules/async/internal/onlyOnce.js:12:16
    at callback (/home/botci/project/node_modules/thread-loader/dist/WorkerPool.js:163:21)
    at /home/botci/project/node_modules/thread-loader/dist/WorkerPool.js:190:15
    at /home/botci/project/node_modules/async/internal/map.js:32:9
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

```

**Steps to reproduce**

`yarn build`

**Expected behavior**
I can build successfully

**Environment**

 - Browser (if applicable): Circle CI
 - React-PDF version: 4.2.0
 - React version: 16.8.5
 - Webpack version (if applicable): 4.46.0
 - Node version: 14.17.0
 
 
![image](https://user-images.githubusercontent.com/26110369/123667286-35732580-d864-11eb-8fb0-f24dd6f9ed97.png)

**Comment by wojtekmaj** [comment]
* Nothing here looks like it's thrown by React-PDF or any of its dependencies
* Old version of React-PDF used

Sorry, I won't be able to help here!
